
[auth]
enable_signup = true

[functions]
[functions.create-invoice]
verify_jwt = false

[functions.create-profile-from-airtable]
verify_jwt = false

[functions.get-secret]
verify_jwt = true

[functions.send-email-reminder]
verify_jwt = true
